[project]
name = "api"
version = "0.1.0"
description = ""
authors = [
    {name = "p.hardy",email = "pierre.hardy@egis-group.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry]
packages = [{include = "api", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
