name: Build and test Frontend

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage on frontend app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ./packages/frontend
        run: yarn install && yarn playwright install chromium
    
      - name: Build package
        working-directory: ./packages/frontend
        run: yarn build

      - name: Run tests
        working-directory: ./packages/frontend
        run: yarn coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}