on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      working-directory: ./packages/frontend
      run: yarn install && yarn playwright install chromium
    - name: 'Test frontend'
      working-directory: ./packages/frontend
      run: yarn coverage
    - uses: googleapis/release-please-action@v4
      with:
        release-type: simple